### ISSUE TITLE
Binomial estimation - state isssue with new data

### ISSUE THREAD

**Issue by JohnnyDoorn** [jasp-stats/jaspLearnBayes#137]
The binomial estimation learnbayes module does not update when changing the observed count data.
See screenshot below - where data are added, but posterior is not updated:
![image](https://user-images.githubusercontent.com/15704203/230014283-b0ddac80-1da1-4da8-a932-ec4c95bc88e5.png)

commit id: https://github.com/jasp-stats/jasp-desktop/commit/8f9be0d7ac431a2e7b0e6d927814586e844a3c0a

**Comment by EJWagenmakers** [comment]
This was not assigned. Frantisek, can you check?
